IntegraSoft_Front/IntegraSoft_Front/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('works/', include('mantenedor_works.urls') ), 
    path("cuenta/", include('cuenta.urls')),
    path('novedades/', include('novedades.urls')), 
    path('', include('templates_generales.urls') ),
   
]


#ignore: llamamos a IndewsView desde nuestra app "templates_generales" debido a que no tenemos
#views como tal en nuestra app de configuracion, después de llamar a las views de nuestra app podemos 
#utilizar el login_required, solucionamos el problema de logout que redirigia al admin con un "next page"

IntegraSoft_Front/cuenta/urls.py
from django.urls import path
from . import views

app_name = 'cuenta'

urlpatterns = [
    path('', views.index, name="index_cuenta"),
]

#la ruta para cuenta está clutch

IntegraSoft_Front/mantenedor_works/urls.py
# from django.urls import path
# from django.contrib.auth.decorators import login_required
# from . import views

# urlpatterns = [
#     path('', login_required (views.index), name="index_mantenedor_usuarios"),
#     path('usuarios', views.Persona, name="usuarios_mantenedor_works"),
#     path('buscar_usuarios', views.buscar_usuarios, name="buscar_usuarios_mantenedor_works"),
#     path('obtener_opciones_por_base/', views.obtener_opciones_por_base, name='obtener_opciones_por_base_mantenedor_works'),
#     path('works/buscar_usuarios/detalles/<str:base_datos>/<str:user_id>/', views.detalles_usuario, name='detalles_usuario_mantenedor_works')


# ]
# #los works ya están clutcheados por parte del login_Required

from django.urls import path
from . import views

app_name = 'workers' 

urlpatterns = [
   path('', views.index, name="index_mantenedor_usuarios"),  # Quita login_required
   path('proxy-departments/', views.proxy_to_departments, name='proxy-departments'),
   path('buscar_usuarios', views.buscar_usuarios, name="buscar_usuarios_mantenedor_works"),
   path('detalles/<str:base_datos>/<str:user_id>/', views.detalles_usuario, name='detalles_usuario'),
   path('cargar_mas_usuarios/', views.cargar_mas_usuarios, name='cargar_mas_usuarios'),
]

IntegraSoft_Front/templates_generales/urls.py
from django.urls import path
from .views import login_view, home_view, logout_view

app_name = 'accounts'

urlpatterns = [
    path('home/', home_view, name='index_home'),
    path('', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    # Otras URLs
]

IntegraSoft_Front/templates_generales/models.py
from django.db import models

IntegraSoft_Front/templates_generales/views.py
import requests
from django.shortcuts import render, redirect
from django.contrib import messages
from IntegraSoft_Front.settings import API_BASE_URL
from Decorators.auth_decorator import token_auth
from django.utils import timezone
def login_view(request):
    # Verifica si el usuario ya está autenticado
    if 'token' in request.session:
        # Si ya hay un token en la sesión, redirige al usuario a la página principal
        return redirect('accounts:index_home')

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
    
        # Realiza la solicitud de autenticación a tu API
        login_url = f"{API_BASE_URL}/login/"
        response = requests.post(login_url, json={'username': username, 'password': password})

        if response.status_code == 200:
            # El usuario está autenticado, guarda el token en la sesión
            token = response.json().get('token')
            request.session['token'] = token
            request.session['user'] = username
            request.session.save()
            # Redirige a la página principal
            return redirect('accounts:index_home')
        else:
            # Si el login falla, muestra un mensaje de error
            messages.error(request, 'Proporcionó credenciales incorrectas, intentelo de nuevo por favor.')
    # Renderiza la plantilla de login si no es una solicitud POST o si el login falla
    return render(request, 'templates_generales/login.html')

@token_auth
def home_view(request):
    # Esta es la vista protegida que solo los usuarios autenticados pueden ver
    user = request.session['user']
    return render(request, 'templates_generales/home.html',{'user': user})

def logout_view(request):
    # Elimina toda la sesión
    request.session.flush()

    # Redirige al usuario a la página de inicio de sesión
    return redirect('accounts:login')

#validacion de usuario conectado antes de pasar al index

IntegraSoft_Front/templates_generales/templates/templates_generales/home.html
{% extends 'templates_generales/template_main.html' %}
{% load static %}
{% block content %}

<div class="container mt-4 text-center">
  <h1>Nos encontramos trabajando en esto</h1>
  <img src="{% static '/images/contruccion.png' %}"  alt="Trabajando" class="img-fluid mx-auto d-block" style="max-width:30%; height:auto;">
  <p class="mt-3">Estamos haciendo mejoras. ¡Vuelve pronto!</p>
</div>
{% endblock %}
  

IntegraSoft_Front/templates_generales/templates/templates_generales/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>IntegraSoft</title>
    <link href="{% static 'bootstrap/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicons/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="theme-color" content="#ffffff">
</head>

<body>
    <style>
        .message-success {
          color: #2e8b57; /* o cualquier código de color verde claro que prefieras */
        }
      
        .btn-conectar {
            background-color: #32CD32; /* Color verde claro */
            border-color: #32CD32; /* Color verde claro */
            transition: background-color 0.3s, border-color 0.3s; /* Para suavizar la transición */
          }
        
          /* Cambia los estilos cuando el ratón pasa por encima del botón */
        .btn-conectar:hover {
            background-color: #2e8b57; /* Un verde un poco más oscuro para el efecto hover */
            border-color: #2e8b57; /* Un verde un poco más oscuro para el borde en hover */
          }
      
        /* Esta clase será añadida por JavaScript para ocultar el mensaje */
        .hidden {
          display: none;
        }
      </style>
      
    <div class="container-fluid min-vh-100 d-flex align-items-center px-0">
        <div class="login-card-container">
            <!-- Área de la imagen -->
            <div class="login-image-side col-md-9">
                <!-- La imagen del lado izquierdo se mostrará en todas las pantallas -->
            </div>
            <!-- Área del formulario -->
            <div class="form-side col-md-3">
                <div class="w-100">
                    <!-- Contenido del formulario -->
                    <img src="{% static 'images/integrasoft_png.PNG' %}" alt="Logo" class="img-fluid mb-4">
                    <div class="saludo">
                        <h2 id="saludo">¡Hola, <span id="parte-del-dia"></span>!</h2>
                    </div>

                    <script>
                        window.onload = function() {
                            var parteDelDia = document.getElementById("parte-del-dia");
                            var hora = new Date().getHours();
                        
                            if (hora < 12) {
                                parteDelDia.innerHTML = "buenos días";
                            } else if (hora < 18) {
                                parteDelDia.innerHTML = "buenas tardes";
                            } else {
                                parteDelDia.innerHTML = "buenas noches";
                            }
                        };

                        document.addEventListener('DOMContentLoaded', function () {
                            // Busca el mensaje de éxito y verifica si existe
                            var successMessage = document.querySelector('.message-success');
                            if (successMessage) {
                              // Establece un temporizador para ocultar el mensaje después de 3 segundos (3000 milisegundos)
                              setTimeout(function () {
                                successMessage.classList.add('hidden');
                              }, 3000);
                            }
                          });
                        </script>
                        
                            
                    <form method="post">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="username" class="form-label">Usuario:</label>
                        <input type="text" name="username" class="form-control" required>
                    </div>
                    <div class="mb-3">
                        <label for="password" class="form-label">Contraseña:</label>
                        <input type="password" name="password" class="form-control" required>
                    </div>
                    <div class="d-flex justify-content-between align-items-center mb-4">
                       
                        <button type="submit" class="btn btn-conectar">Conectar</button>

                    </div>
                    {% if messages %}
                    <div class="message-container">
                      {% for message in messages %}
                        <div class="{{ message.tags }} message-success">{{ message }}</div>
                      {% endfor %}
                    </div>
                  {% endif %}
                  
                </form>
            </div>
        </div>
    </div>
    <script src="{% static 'bootstrap/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

IntegraSoft_Front/templates_generales/templates/templates_generales/template_main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>IntegraSoft</title>
    <link href="{% static '/bootstrap/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static '/bootstrap/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static '/css/styles.css' %}" rel="stylesheet">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicons/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="theme-color" content="#ffffff">
    {% block styles %}
    <link href="{% static '/css/styles.css' %}" rel="stylesheet">
    <style>
        
        html {
            height: 100%;
        }
        body {
            display: flex;
            flex-direction: column;
            min-height: 100%;
            margin: 0;
        }
        .content-wrapper {
            flex: 1;
        }


        footer {
            position: relative;
            background-color: #4CAF50; /* Color de fondo del footer */
            color: white; /* Color del texto del footer */
            text-align: center;
            padding: 10px 0;
        }

        footer:before {
            font-size: 0;
            width: 100%;
            height: 5px;
            display: block;
            position: absolute;
            left: 0;
            top: 0;
            content: "";
            background-size: 100%;
            background-repeat: repeat-y;
            background-position: center;
            background-image: url({% static "/images/border-colors.svg" %});
        }

        .navbar-nav .nav-link,
        .navbar-brand {
            color: white;
            
        }
        /* Estilo para el elemento de navegación actual */
        .navbar-nav .nav-item .nav-link.active {
            background-color: white;
            color: black;
            
          
        }
    </style>
    {% endblock styles %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-success">
        <div class="container">
            <a class="navbar-brand" href="{% url 'accounts:index_home' %}">{{ user | upper }} BIENVENIDO A INTEGRASOFT DE CCU</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link {% if request.resolver_match.url_name == 'index_home' %}active{% endif %}" href="{% url 'accounts:index_home' %}">Inicio</a>
                    </li>
                    <li class="nav-item">
                {% with "works/" as works_path %}
    <a class="nav-link {% if request.path == '/works/' or works_path in request.path %}active{% endif %}" href="{% url 'workers:index_mantenedor_usuarios' %}">Servicios</a>
{% endwith %}

                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.resolver_match.url_name == 'index_novedades' %}active{% endif %}" href="{% url 'index_novedades' %}">Novedades</a>
                    </li> 
                    <li class="nav-item">
                        <a class="nav-link {% if request.resolver_match.url_name == 'index_cuenta' %}active{% endif %}" href="{% url 'cuenta:index_cuenta' %}">Cuenta</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <div class="user-image-container-nav">
                                <img src="{% static 'icons/user.png' %}" alt="User Image" class="user-image">                           
                            </div>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userDropdown">
                            <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Cerrar sesión</a></li>
                        </ul>
                    </li>
                    
                </ul>
            </div>
        </div>
    </nav>


   <div class="content-wrapper">
    <div class="container mt-4">
        <h1></h1>
        {% block content %}
        {% endblock %}
    </div>
    </div>
    <footer class="bg-success text-white text-center py-3">
        <div class="disclaimer text-center roboto clearfix left uppercase">
            <p class="bold">&copy; 2023 Desarrollado por el área de Operaciones de CCU</p>
        </div>
    </footer>

    
    <script src="{% static 'bootstrap/bootstrap.bundle.min.js' %}"></script>
    
</body>
</html>