IntegraSoft_Front/IntegraSoft_Front/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('works/', include('mantenedor_works.urls') ), 
    path("cuenta/", include('cuenta.urls')),
    path('novedades/', include('novedades.urls')), 
    path('', include('templates_generales.urls') ),
   
]


#ignore: llamamos a IndewsView desde nuestra app "templates_generales" debido a que no tenemos
#views como tal en nuestra app de configuracion, después de llamar a las views de nuestra app podemos 
#utilizar el login_required, solucionamos el problema de logout que redirigia al admin con un "next page"

IntegraSoft_Front/cuenta/urls.py
from django.urls import path
from . import views

app_name = 'cuenta'

urlpatterns = [
    path('', views.index, name="index_cuenta"),
]

#la ruta para cuenta está clutch

IntegraSoft_Front/mantenedor_works/urls.py
# from django.urls import path
# from django.contrib.auth.decorators import login_required
# from . import views

# urlpatterns = [
#     path('', login_required (views.index), name="index_mantenedor_usuarios"),
#     path('usuarios', views.Persona, name="usuarios_mantenedor_works"),
#     path('buscar_usuarios', views.buscar_usuarios, name="buscar_usuarios_mantenedor_works"),
#     path('obtener_opciones_por_base/', views.obtener_opciones_por_base, name='obtener_opciones_por_base_mantenedor_works'),
#     path('works/buscar_usuarios/detalles/<str:base_datos>/<str:user_id>/', views.detalles_usuario, name='detalles_usuario_mantenedor_works')


# ]
# #los works ya están clutcheados por parte del login_Required

from django.urls import path
from . import views

app_name = 'workers' 

urlpatterns = [
   path('', views.index, name="index_mantenedor_usuarios"),  # Quita login_required
   path('proxy-departments/', views.proxy_to_departments, name='proxy-departments'),
   path('buscar_usuarios', views.buscar_usuarios, name="buscar_usuarios_mantenedor_works"),
   path('detalles/<str:base_datos>/<str:user_id>/', views.detalles_usuario, name='detalles_usuario'),
   path('cargar_mas_usuarios/', views.cargar_mas_usuarios, name='cargar_mas_usuarios'),
]

IntegraSoft_Front/mantenedor_works/models.py
from django.db import models

# Create your models here.

IntegraSoft_Front/mantenedor_works/forms.py
from django import forms

class SearchForm(forms.Form):
    person_number = forms.CharField(label='Person Number', required=False)
    national_id = forms.CharField(label='National ID', required=False)
    first_name = forms.CharField(label='First Name', required=False)
    last_name = forms.CharField(label='Last Name', required=False)
    person_id_hcm = forms.CharField(label='Person Id HCM', required=False)

IntegraSoft_Front/mantenedor_works/views.py
import logging
import requests 
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from mantenedor_works.services.hcm.worker_service_hcm import WorkerServiceHcm
from mantenedor_works.services.peoplesoft.worker_service_peoplesoft import WorkerServicePeopleSoft
from mantenedor_works.services.department.department import DepartmentService
from Decorators.auth_decorator import token_auth
from urllib.parse import unquote
from django.urls import reverse
from IntegraSoft_Front import settings
from django.http import JsonResponse
from urllib.parse import unquote

logger = logging.getLogger(__name__)
@token_auth
def index(request):
    user = request.session['user']
    return render(request, 'mantenedor_works/index_usuarios.html',{'user': user, 'api_base_url': settings.API_BASE_URL})

@token_auth
def proxy_to_departments(request):
    base_datos = request.GET.get('base_datos', 'hcm')
    search = request.GET.get('name', '')  # Cambiado a 'name' para coincidir con el parámetro de la API

    service = DepartmentService(request)
    response = service.get_departments(base_datos, search_query=search)
    return JsonResponse(response)

def get_worker_service(base_datos, request):
    if base_datos == 'HCM':
        return WorkerServiceHcm(request)
    elif base_datos == 'PeopleSoft':
        return WorkerServicePeopleSoft(request)
    else:
        raise ValueError("Base de datos no soportada")
    


@token_auth
def buscar_usuarios(request):
    firstName = ""
    lastName = ""  
    personNumber = ""  
    departamentoId = ""
    base_datos = ""  
    user = request.session.get('user', {})
    error_message = None  
    resultados = []  # Lista para almacenar los resultados
    has_more = False
    next_url = None

    # Obtén el offset de la URL para HCM
    offset = request.GET.get('offset', None)

    if request.method == 'POST':
        firstName = request.POST.get('firstName', '')
        lastName = request.POST.get('lastName', '')
        personNumber = request.POST.get('personNumber', '')
        departamentoId = request.POST.get('departamento', '')
        base_datos = request.POST.get('base_datos', '')

        if not base_datos:
            error_message = 'Debe seleccionar una base de datos.'
        elif not (firstName or lastName or personNumber or departamentoId):
            error_message = 'Debe llenar al menos un campo para la búsqueda.'
        else:
            try:
                worker_service = get_worker_service(base_datos, request)
                if base_datos == 'HCM':
                    resultados_hcm = worker_service.buscar_usuarios_por_nombre(
                        firstName=firstName,
                        lastName=lastName,
                        personNumber=personNumber,
                        department=departamentoId,
                        offset=offset  # Usa el offset de la URL
                    )
                    # Extraemos la información de paginación si está presente
                    if resultados_hcm and isinstance(resultados_hcm[-1], dict) and 'has_more' in resultados_hcm[-1]:
                        has_more = resultados_hcm[-1]['has_more']
                        next_url = resultados_hcm[-1]['next_url']
                        resultados_hcm = resultados_hcm[:-1]  # Removemos el elemento de paginación
                    resultados = resultados_hcm

                elif base_datos == 'PeopleSoft':
                    response = worker_service.buscar_usuarios_por_nombre(
                        firstName=firstName,
                        lastName=lastName,
                        personNumber=personNumber,
                        department=departamentoId
                    )
                    if response:
                        resultados, has_more, next_url = response
                    else:
                        resultados, has_more, next_url = ([], False, None)  # Valores predeterminados en caso de None
                print("siguiente_url", next_url)

            except ValueError as e:
                logger.error(f"Error al buscar usuarios: {e}")
                error_message = "Ocurrió un error al buscar usuarios."

    return render(request, 'mantenedor_works/buscar_usuarios.html', {
        'path': request.path,
        'usuarios': resultados,
        'firstName': firstName,
        'lastName': lastName,
        'personNumber': personNumber,
        'departamentoId': departamentoId,
        'base_datos': base_datos,
        'api_base_url': settings.API_BASE_URL,
        'user': user,
        'error_message': error_message,
        'has_more': has_more,
        'next_url': next_url
    })

# views.py
# @token_auth
# def detalles_usuario(request, base_datos, user_id):
#     user = request.session.get('user', {})
#     detalles_hcm = None
#     detalles_peoplesoft = None
#     diferencias = {}  # Asegúrate de inicializar la variable diferencias

#     service_hcm = WorkerServiceHcm(request)
#     service_peoplesoft = WorkerServicePeopleSoft(request)

#     if base_datos == 'HCM':
#         detalles_hcm = service_hcm.get_worker(user_id)
#         detalles_peoplesoft = service_peoplesoft.get_detalle_usuario_peoplesoft(user_id)
        
#     elif base_datos == 'PeopleSoft':
#         detalles_peoplesoft = service_peoplesoft.get_detalle_usuario_peoplesoft(user_id)
#         detalles_hcm = service_hcm.get_worker(user_id)


#     if detalles_hcm or detalles_peoplesoft:
#         diferencias = comparar_datos(detalles_hcm, detalles_peoplesoft)
#         detalles_hcm['complete_name'] = detalles_hcm.get('complete_name', '').title()
#         detalles_peoplesoft['name'] = detalles_peoplesoft.get('name', '').title()    
       
       

#     # Agrega un mensaje si no se encuentran detalles
#     mensaje_hcm = 'No se encontraron datos en HCM para este usuario.' if not detalles_hcm else ''
#     mensaje_peoplesoft = 'No se encontraron datos en PeopleSoft para este usuario.' if not detalles_peoplesoft else ''

#     context = {
#         'user': user,
#         'base_datos': base_datos,
#         'detalles_hcm': detalles_hcm,
#         'detalles_peoplesoft': detalles_peoplesoft,
#         'diferencias': diferencias,
#         'mensaje_hcm': mensaje_hcm,
#         'mensaje_peoplesoft': mensaje_peoplesoft
#     }
    
   
#     return render(request, 'mantenedor_works/hcm_peoplesoft.html', context)

@token_auth
def detalles_usuario(request, base_datos, user_id):
    user = request.session.get('user', {})
    detalles_hcm = None
    detalles_peoplesoft = None
    diferencias = {}
    mensaje_hcm = ''
    mensaje_peoplesoft = ''

    service_hcm = WorkerServiceHcm(request)
    service_peoplesoft = WorkerServicePeopleSoft(request)

    if base_datos == 'HCM':
        detalles_hcm = service_hcm.get_worker(user_id)
        detalles_peoplesoft = service_peoplesoft.get_detalle_usuario_peoplesoft(user_id)
        mensaje_peoplesoft = 'No se encontraron datos en PeopleSoft para este usuario.' if not detalles_peoplesoft else ''
    elif base_datos == 'PeopleSoft':
        detalles_peoplesoft = service_peoplesoft.get_detalle_usuario_peoplesoft(user_id)
        detalles_hcm = service_hcm.get_worker(user_id)
        mensaje_hcm = 'No se encontraron datos en HCM para este usuario.' if not detalles_hcm else ''


    if detalles_hcm and detalles_peoplesoft:
        diferencias = comparar_datos(detalles_hcm, detalles_peoplesoft)
        detalles_hcm['complete_name'] = detalles_hcm.get('complete_name', '').title() if detalles_hcm else 'No disponible'
        detalles_peoplesoft['name'] = detalles_peoplesoft.get('name', '').title() if detalles_peoplesoft else 'No disponible'

    context = {
        'user': user,
        'base_datos': base_datos,
        'detalles_hcm': detalles_hcm,
        'detalles_peoplesoft': detalles_peoplesoft,
        'diferencias': diferencias,
        'mensaje_hcm': mensaje_hcm,
        'mensaje_peoplesoft': mensaje_peoplesoft
    }
    
    return render(request, 'mantenedor_works/hcm_peoplesoft.html', context)

def comparar_datos(detalles_hcm, detalles_peoplesoft):
    diferencias = {}
    mapeo_campos = {
        'complete_name':'name',
        'person_number': 'emplid',
        'date_of_birth': 'birthdate',
        'last_name': 'last_name',
        'first_name': 'first_name',
        'middle_names': 'middle_name',
        'legal_employer_code':'company',
        'country': 'country',
        'addressLine1': 'address1',
        'addressLine2': 'address2',
        'town_or_city': 'city',
        'system_person_type': 'per_org',
        'effective_start_date': 'hire_dt',
        'business_unit_name': 'business_unit',
        'business_unit_name': 'business_unit_descr',
        'ccu_codigo_centro_costo': 'deptid',
        'department_name': 'dept_descr',
        'job_code': 'jobcode',
        'standard_working_hours': 'std_hours',
        'locationCode': 'location',
        'managerAssignmentNumber': 'supervisor_id',
        'email_address': 'email'
    }

    for campo_hcm, campo_ps in mapeo_campos.items():
            # Comprobación de None antes de intentar llamar a .get()
            valor_hcm = detalles_hcm.get(campo_hcm, None) if detalles_hcm else None
            valor_ps = detalles_peoplesoft.get(campo_ps, None) if detalles_peoplesoft else None

            # Si ambos valores son iguales (o ambos None), no hay diferencia
            if valor_hcm == valor_ps:
                diferencias[campo_hcm] = False
            else:
                # Hay una diferencia si alguno de los valores es None, o si son diferentes
                diferencias[campo_hcm] = True

    return diferencias



@token_auth
def cargar_mas_usuarios(request):
    next_url = request.GET.get('next_url')
    base_datos = request.GET.get('base_datos', 'HCM')  # O un valor por defecto

    # Impresiones para depuración
    print("Base de datos seleccionada:", base_datos)
    print("URL siguiente:", next_url)

    if not next_url:

IntegraSoft_Front/mantenedor_works/templates/mantenedor_works/buscar_usuarios.html
{% extends 'mantenedor_works/index_usuarios.html' %}
{% load static %}

{% block grilla_usuarios %}
{% block css %} 
<link rel="stylesheet" type="text/css" href="{% static 'css/botones.css' %}">
{% endblock css %}

<div class="container">
  {% if usuarios %}
    <h2>Resultados de Búsqueda:</h2>
    <div class="table-responsive">
      <table class="table" id="tabla-resultados">
        <caption>Resultados de búsqueda</caption>
        <thead>
          <tr>
            <th>Número de Persona</th>
            <th>Nombre Completo</th>
            <th>Departamento</th>
            <th>Acciones</th>
          </tr>
        </thead>
        <tbody>
          {% for usuario in usuarios %}
          <tr>
              <td>{{ usuario.personNumber }}</td>
              <td>{{ usuario.nombre_completo }}</td>
              <td>{{ usuario.department_name }}</td>
              <td>
                  {% if base_datos and usuario.personNumber %}
                      <a href="{% url 'workers:detalles_usuario' base_datos=base_datos user_id=usuario.personNumber %}" class="btn btn-detalle">Ver Detalle</a>
                  {% else %}
                      <span>No disponible</span>
                  {% endif %}
              </td>
          </tr>

          {% empty %}
          <tr>
              <td colspan="4">No se encontraron resultados.</td>
          </tr>
          {% endfor %}
        </tbody>
 
      </table>
      {% if has_more %}
      <div class="text-center">
        <button id="cargar-mas" data-next-url="{{ next_url }}">Cargar Más</button>

        </div>
    {% endif %}
    </div>  
    <div id="loading-spinner" style="display: none;" class="text-center">
      <div class="spinner-border" role="status">
          <span class="sr-only">Cargando...</span>
      </div>
  </div>
  
  {% else %}
    <p>No se encontraron resultados.</p>
  {% endif %}
</div>

{% block js %}
<script type="text/javascript">
  // Definir las variables nextUrl y nextOffset con los valores de Django
  var nextUrl = "{{ next_url|default:'' }}";  // Utiliza el valor predeterminado si next_url no está definido
  var nextOffset = "{{ offset|default:'' }}";  // Utiliza el valor predeterminado si offset no está definido
  var baseDatos = "{{ base_datos }}";
  console.log(baseDatos);
</script>
<script type="text/javascript" src="{% static 'js/more_results.js' %}"></script>

{% endblock js %}

{% endblock grilla_usuarios %}

IntegraSoft_Front/mantenedor_works/templates/mantenedor_works/detalles_usuario.html
{% extends 'templates_generales/template_main.html' %}
{% load static %}


{% block content %}

<div class="container">
  <style>
    .align-right {
      text-align: right;
    }
  </style>
  {% block css %} <link rel="stylesheet" type="text/css" href="{% static 'css/botones.css' %}">{% endblock css %} 
  {% block script_cargar %} <script src="{% static 'js/listener.js' %}"></script>{% endblock script_cargar %}
  {% block script_regreso %} <script src="{% static 'js/regreso.js'%}"></script>{% endblock script_regreso %}
  <div class="align-right">
    <a id="regresar_formulario" href="{% url 'workers:buscar_usuarios_mantenedor_works' %}" class="btn btn-primary">Regresar a la búsqueda</a>
  </div>

  <h1 class="text-center mt-4">Detalles del Usuario</h1>
  <div class="mt-4">
    {% if base_datos == 'HCM' and detalles_hcm %}
      <div class="nombre-completo-contenedor">
        <h2 class="nombre-completo-panel"><strong>Usuario:</strong>{{ detalles_hcm.complete_name }}</h2>
        <p class="numero-persona"><strong>Número de Persona:</strong> {{ detalles_hcm.person_number }}</p>
      </div>
    {% elif base_datos == 'PeopleSoft' and detalles_peoplesoft %}
      <div class="nombre-completo-contenedor">
        <h2 class="nombre-completo-panel"><strong> Usuario: </strong>{{ detalles_peoplesoft.name }}</h2>
        <p class="numero-persona"><strong>ID Empleado:</strong> {{ detalles_peoplesoft.emplid }}</p>
      </div>
    {% else %}
      <p>No se encontraron datos para este usuario.</p>
    {% endif %}
    <div class="row">
      {% block content_comparador %} {% endblock content_comparador %}
    </div>
  </div>
  
</div>

{% endblock content %}

IntegraSoft_Front/mantenedor_works/templates/mantenedor_works/index_usuarios.html
{% extends 'templates_generales/template_main.html' %}
{% load static %}
{% block content %}
<script type="text/javascript">
    var apiBaseUrl = "{{ api_base_url }}";
</script>
{% block jquery %}<script src="{% static 'js/jquery.min.js' %}"></script>{% endblock jquery %}
{% block css_select %}<link rel="stylesheet" type="text/css" href="{% static 'select2/css/select2.min.css' %}">{% endblock css_select %}
{% block jquery_js %}<script src="{% static 'select2/js/select2.full.min.js' %}"></script>{% endblock jquery_js %}
{% block script_limpiar %} <script src="{% static 'js/limpiar.js' %}"></script>{% endblock script_limpiar %}
{% block script_dpt %} <script src="{% static 'js/dpt.js' %}"></script> {% endblock script_dpt %}
<div class="container">
    <h1 class="text-center mt-4">Formulario de Búsqueda</h1>
    <form action="{% url 'workers:buscar_usuarios_mantenedor_works' %}" method="POST" class="mt-4">
        {% csrf_token %}

        <!-- Dropdown para seleccionar la base de datos -->
        <div class="row mb-3">
            <div class="col-md-4">
                <label for="base_datos">Base de Datos:</label>
                <select id="base_datos" name="base_datos" class="form-control" onchange="habilitarCampos()">
                    <option value="">Seleccionar base de datos</option>
                    <option value="HCM" {% if base_datos == 'HCM' %}selected{% endif %}>HCM</option>
                    <option value="PeopleSoft" {% if base_datos == 'PeopleSoft' %}selected{% endif %}>PeopleSoft</option>
                </select>
                <span id="mensaje" class="text-success" style="display: none; opacity: 1; transition: opacity 2s;">
                    Para iniciar el proceso de búsqueda primero debe seleccionar una base de datos
                </span>
            </div>
                <!-- Departamento -->
            <div class="col-md-4">
                
                <label for="departamentoDropdown">Departamento:</label>
                    <select id="departamentoDropdown" name="departamento" class="form-control">
                        <option value="">Seleccione un departamento</option>
                        {% for departamento in departamentos %}
                        <option value="{{ departamento.dept_id }}" {% if departamento.dept_id == departamentoId %}selected{% endif %}>
                            {{ departamento.name }}
                        </option>
                        {% endfor %}
                    </select>
                </div>
                    
           
                
        </div>

        <!-- Campos de búsqueda -->
        <div class="row">
            <div class="col-md-4">
                <label for="personNumber">Número de Persona:</label>
                <input type="text" id="personNumber" name="personNumber" class="form-control" value="{{ personNumber|default:'' }}">
            </div>
        </div>
        
        <div class="row">
            <div class="col-md-4">
                <label for="firstName">Nombre:</label>
                <input type="text" id="firstName" name="firstName" class="form-control" value="{{ firstName|default:'' }}"> 
            </div>
            <div class="col-md-4">
                <label for="lastName">Apellido:</label>
                <input type="text" id="lastName" name="lastName" class="form-control" value="{{ lastName|default:'' }}"> 
            </div>
        </div>
        
        

        {% if error_message %}
        <div class="alert alert-danger mt-3">
            {{ error_message }}
        </div>
        {% endif %}
    
        <div class="d-flex align-items-center mt-3">
            <button id="buscar" type="submit" class="btn btn-primary">Buscar</button>
            <button id="limpiar" type="button" class="btn btn-danger" onclick="event.preventDefault(); limpiarFormulario();">Limpiar</button>
        </div>
    </form>
    <div id="grillaUsuarios">
        {% block grilla_usuarios %}
        <!-- Aquí se mostrarán los resultados de la búsqueda -->
        {% endblock grilla_usuarios %}
    </div>
</div>

{% block script_sistema %} <script src="{% static 'js/boton_sistema.js' %}"></script>{% endblock script_sistema %}
{% block css %} <link rel="stylesheet" type="text/css" href="{% static 'css/botones.css' %}">{% endblock css %}
{% block script_habilitar%} <script src="{% static 'js/habilitar.js' %}"></script>{% endblock script_habilitar %}
{% endblock content %}